# Generated by Django 4.0.5 on 2022-06-19 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akeray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
