# Generated by Django 4.0.5 on 2022-06-20 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akeray', '0003_alter_category_options_category_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='renter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
